"""Build or refresh the Tier A LLM harvest queue from corpus scan reports."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from scripts.corpus.corpus_presets import REPO_ROOT, corpus_checkout_root
from scripts.harvest.harvest_state import HarvestState, load_state, save_state, utc_now_iso

DEFAULT_REPORTS_DIR = REPO_ROOT / "corpus-reports"
DEFAULT_QUEUE_PATH = REPO_ROOT / ".j2py" / "harvest" / "queue.txt"
MAX_QUEUE_SIZE = 50


@dataclass(frozen=True)
class QueueEntry:
    preset: str
    path: str
    loc: int


def _report_paths(reports_dir: Path) -> list[Path]:
    if not reports_dir.is_dir():
        return []
    return sorted(reports_dir.glob("*.json"))


def _is_tier_a(file_metric: dict[str, object]) -> bool:
    path = str(file_metric.get("path", ""))
    if path.endswith("package-info.java"):
        return False
    if not file_metric.get("parse_ok", False):
        return False
    if file_metric.get("syntax_ok", True):
        return False
    if float(file_metric.get("coverage", 0)) != 1.0:
        return False
    return int(file_metric.get("unhandled_count", 0)) == 0


def _loc_estimate(path: str) -> int:
    file_path = Path(path)
    if not file_path.is_file():
        return 999_999
    try:
        return len(file_path.read_text(encoding="utf-8", errors="replace").splitlines())
    except OSError:
        return 999_999


def collect_tier_a_entries(reports_dir: Path) -> tuple[list[QueueEntry], list[str]]:
    """Return Tier A entries and report paths used."""
    entries: list[QueueEntry] = []
    used_reports: list[str] = []
    seen_paths: set[str] = set()

    for report_path in _report_paths(reports_dir):
        try:
            payload = json.loads(report_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        files = payload.get("files")
        if not isinstance(files, list):
            continue
        preset = str((payload.get("metadata") or {}).get("preset", report_path.stem))
        try:
            used_reports.append(str(report_path.relative_to(REPO_ROOT)))
        except ValueError:
            used_reports.append(str(report_path))
        for file_metric in files:
            if not isinstance(file_metric, dict) or not _is_tier_a(file_metric):
                continue
            path = str(file_metric["path"])
            if path in seen_paths:
                continue
            seen_paths.add(path)
            entries.append(
                QueueEntry(
                    preset=preset,
                    path=path,
                    loc=_loc_estimate(path),
                )
            )

    entries.sort(key=lambda item: (item.loc, item.path))
    return entries[:MAX_QUEUE_SIZE], used_reports


def queue_is_stale(
    queue_path: Path,
    report_paths: list[Path],
    *,
    force: bool = False,
) -> bool:
    if force or not queue_path.is_file():
        return True
    queue_mtime = queue_path.stat().st_mtime
    for report_path in report_paths:
        if report_path.is_file() and report_path.stat().st_mtime > queue_mtime:
            return True
    return False


def render_queue(entries: list[QueueEntry], *, corpus_root: Path) -> str:
    lines = [
        "# Tier A harvest queue: coverage==1.0, syntax_ok=false, unhandled_count==0",
        "# Generated by scripts/harvest/build_harvest_queue.py",
        f"# Built: {datetime.now(UTC).replace(microsecond=0).isoformat().replace('+00:00', 'Z')}",
        f"# Corpus clones: {corpus_root}/",
        "#",
        "# Run:",
        "#   make harvest-promote",
        "#   make harvest-gemini OFFSET=0 LIMIT=2",
        "",
    ]
    for index, entry in enumerate(entries, start=1):
        rel = entry.path
        try:
            rel = str(Path(entry.path).resolve().relative_to(corpus_root.parent))
        except ValueError:
            rel = entry.path
        lines.append(
            f"# {index:2d} [{entry.preset}] loc={entry.loc} {rel}",
        )
        lines.append(entry.path)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_queue(
    *,
    queue_path: Path = DEFAULT_QUEUE_PATH,
    reports_dir: Path = DEFAULT_REPORTS_DIR,
    force: bool = False,
    state_path: Path | None = None,
) -> tuple[Path, HarvestState, bool]:
    """Build queue when missing or stale. Returns (path, state, rebuilt)."""
    report_paths = _report_paths(reports_dir)
    stale = queue_is_stale(queue_path, report_paths, force=force)
    state = load_state(state_path)

    if not stale:
        from scripts.harvest.run_llm_harvest import load_paths_from_file

        paths = load_paths_from_file(queue_path)
        state.queue_path = str(queue_path)
        state.queue_total = len(paths)
        return queue_path, state, False

    entries, used_reports = collect_tier_a_entries(reports_dir)
    if not entries:
        raise SystemExit(
            f"No Tier A entries found under {reports_dir}. "
            "Run corpus scans first (see docs/CORPUS_SCOREBOARD.md)."
        )

    corpus_root = corpus_checkout_root()
    queue_path.parent.mkdir(parents=True, exist_ok=True)
    queue_path.write_text(render_queue(entries, corpus_root=corpus_root), encoding="utf-8")

    state.queue_path = str(queue_path)
    state.queue_built_at = utc_now_iso()
    state.queue_source_reports = used_reports
    state.queue_total = len(entries)
    state.harvest_offset = 0
    save_state(state, state_path)
    return queue_path, state, True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--reports-dir",
        type=Path,
        default=DEFAULT_REPORTS_DIR,
        help="Directory with corpus scan JSON reports",
    )
    parser.add_argument(
        "--queue",
        type=Path,
        default=DEFAULT_QUEUE_PATH,
        help="Output queue file path",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Rebuild even when queue is newer than reports",
    )
    args = parser.parse_args()

    path, state, rebuilt = build_queue(
        queue_path=args.queue,
        reports_dir=args.reports_dir,
        force=args.force,
    )
    action = "Rebuilt" if rebuilt else "Kept existing"
    print(f"{action} queue: {path} ({state.queue_total} files, offset={state.harvest_offset})")
    if state.queue_source_reports:
        print(f"Reports: {', '.join(state.queue_source_reports[:5])}")
        if len(state.queue_source_reports) > 5:
            print(f"  … and {len(state.queue_source_reports) - 5} more")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
