"""Render doctor assessment and diff payloads."""

from __future__ import annotations

import json
from html import escape
from typing import Any

from j2py.doctor_models import DoctorAssessment, DoctorDiff


def render_assessment_html(assessment: DoctorAssessment) -> str:
    payload = assessment.payload
    summary = payload["summary"]
    rows = "\n".join(_file_row(item) for item in payload["files"])
    hotspots = payload["hotspots"]
    annotations = "\n".join(
        f"<li><code>{escape(item['name'])}</code>: {item['count']}</li>"
        for item in payload["annotation_inventory"]
    )
    imports = "\n".join(
        f"<li><code>{escape(item['import'])}</code> <span>{escape(item['category'])}</span></li>"
        for item in payload["unresolved_imports"]
    )
    commands = "\n".join(
        f"<li><code>{escape(command)}</code></li>"
        for command in payload["recommended_next_commands"]
    )
    hotspot_columns = "\n".join(
        _hotspot_list(title, items, label_key, value_key)
        for title, items, label_key, value_key in (
            ("Unhandled Node Types", hotspots["unhandled_node_types"], "node_type", "count"),
            ("Warning Reasons", hotspots["semantic_warning_reasons"], "reason", "count"),
            ("Import Packages", hotspots["unresolved_import_packages"], "package", "count"),
            ("Lowest Coverage Files", hotspots["lowest_coverage_files"], "path", "rule_coverage"),
            ("Risk Reasons", hotspots["risk_reasons"], "reason", "count"),
            ("Highest Risk Files", hotspots["highest_risk_files"], "path", "risk_score"),
        )
    )
    readiness_summary = {
        item["bucket"]: item["files"] for item in summary["readiness_distribution"]
    }
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>j2py doctor assessment</title>
<style>
{_ASSESSMENT_CSS}
</style>
</head>
<body>
<header>
  <h1>j2py doctor assessment</h1>
  <span>{escape(str(payload["source"]))}</span>
</header>
<main>
  <section class="summary">
    {_metric("Files", summary["files"])}
    {_metric("Parse failures", summary["parse_failures"])}
    {_metric("Avg coverage", f"{summary['average_rule_coverage']:.0%}")}
    {_metric("Avg risk", f"{summary['average_risk_score']:.1f}/100")}
    {_metric(
        "Risk range",
        f"{summary['min_risk_score']:.1f}-{summary['max_risk_score']:.1f}",
    )}
    {_metric("Semantic warnings", summary["semantic_warnings"])}
    {_metric("Unhandled", summary["unhandled_diagnostics"])}
    {_metric("Unresolved imports", summary["unresolved_imports"])}
    {_metric("Ready files", readiness_summary["ready"])}
    {_metric("Manual-fix files", readiness_summary["requires_manual_fixes"])}
    {_metric("Not-ready files", readiness_summary["not_ready"])}
  </section>
  <section>
    <h2>Files</h2>
    <table>
      <thead>
        <tr>
          <th>File</th>
          <th>Package</th>
          <th>Parse</th>
          <th>Coverage</th>
          <th>Risk</th>
          <th>Band</th>
          <th>Readiness</th>
          <th>Warnings</th>
          <th>Unhandled</th>
          <th>Unresolved Imports</th>
        </tr>
      </thead>
      <tbody>{rows}</tbody>
    </table>
  </section>
  <section class="columns">
    <article>
      <h2>Annotations</h2>
      <ul>{annotations or "<li>No annotations found.</li>"}</ul>
    </article>
    <article>
      <h2>Boundary Candidates</h2>
      <ul>{imports or "<li>No unresolved imports found.</li>"}</ul>
    </article>
  </section>
  <section>
    <h2>Hotspots</h2>
    <div class="columns">{hotspot_columns}</div>
  </section>
  <section>
    <h2>Recommended Next Commands</h2>
    <ul>{commands}</ul>
  </section>
</main>
</body>
</html>
"""


def render_config_suggestions(assessment: DoctorAssessment) -> str:
    payload = assessment.payload
    suggestions = payload["config_suggestions"]
    lines = [
        "# Generated by j2py doctor.",
        "# Review these advisory suggestions before copying them into j2py config.",
        "schema_version: 1",
        f"source: {_yaml_scalar(str(payload['source']))}",
        "config_suggestions:",
    ]
    for key in ("import_map", "type_map", "annotation_map"):
        lines.append(f"  {key}:")
        items = suggestions[key]
        if not items:
            lines.append("    []")
            continue
        for item in items:
            lines.append("    -")
            for item_key in sorted(item):
                lines.append(f"      {item_key}: {_yaml_scalar(item[item_key])}")
    return "\n".join(lines) + "\n"


def render_doctor_diff_text(diff: DoctorDiff) -> str:
    payload = diff.payload
    summary_delta = payload["summary_delta"]
    lines = [
        "Doctor assessment diff",
        f"Before: {payload['before_source']}",
        f"After: {payload['after_source']}",
        "",
        "Summary delta:",
    ]
    for key in sorted(summary_delta):
        delta = summary_delta[key]
        if isinstance(delta, float):
            lines.append(f"  {key}: {delta:+.3f}")
        else:
            lines.append(f"  {key}: {delta:+}")
    lines.extend(
        [
            "",
            f"Parse failures: {len(payload['parse_failures']['removed'])} removed, "
            f"{len(payload['parse_failures']['added'])} added",
            f"Unresolved imports: {len(payload['unresolved_imports']['removed'])} removed, "
            f"{len(payload['unresolved_imports']['added'])} added",
            f"Semantic warnings: {len(payload['semantic_warnings']['removed'])} removed, "
            f"{len(payload['semantic_warnings']['added'])} added",
            f"Unhandled diagnostics: {len(payload['unhandled_diagnostics']['removed'])} removed, "
            f"{len(payload['unhandled_diagnostics']['added'])} added",
        ]
    )
    changed_files = payload["file_changes"]["changed"]
    if changed_files:
        lines.extend(["", "Changed files:"])
        for item in changed_files[:20]:
            line = (
                f"  {item['path']}: coverage {item['rule_coverage_delta']:+.3f}, "
                f"warnings {item['semantic_warnings_delta']:+}, "
                f"unhandled {item['unhandled_delta']:+}, "
                f"unresolved imports {item['unresolved_imports_delta']:+}, "
                f"risk {item['risk_score_delta']:+.1f}, "
                f"readiness {item['readiness_bucket_before']} -> {item['readiness_bucket_after']}"
            )
            if (
                item["risk_score_delta"] == 0.0
                and item["readiness_bucket_before"] == item["readiness_bucket_after"]
            ):
                line = (
                    f"  {item['path']}: coverage {item['rule_coverage_delta']:+.3f}, "
                    f"warnings {item['semantic_warnings_delta']:+}, "
                    f"unhandled {item['unhandled_delta']:+}, "
                    f"unresolved imports {item['unresolved_imports_delta']:+}"
                )
            lines.append(line)
    return "\n".join(lines) + "\n"


def _yaml_scalar(value: str) -> str:
    return json.dumps(value)


def _metric(label: str, value: object) -> str:
    return f"<article><span>{escape(label)}</span><strong>{escape(str(value))}</strong></article>"


def _file_row(item: dict[str, Any]) -> str:
    translation = item["translation"]
    return f"""
<tr>
  <td>{escape(item["path"])}</td>
  <td>{escape(item["package"])}</td>
  <td>{"pass" if item["parse_ok"] else "fail"}</td>
  <td>{translation["rule_coverage"]:.0%}</td>
  <td>{item["risk_score"]:.1f}</td>
  <td>{escape(item["risk_band"])}</td>
  <td>{escape(item["readiness_bucket"])}</td>
  <td>{len(translation["semantic_warnings"])}</td>
  <td>{len(translation["unhandled"])}</td>
  <td>{len(item["unresolved_imports"])}</td>
</tr>"""


def _hotspot_list(
    title: str,
    items: list[dict[str, Any]],
    label_key: str,
    value_key: str = "count",
) -> str:
    rows = "\n".join(
        f"<li><code>{escape(str(item[label_key]))}</code>: "
        f"{escape(str(item.get(value_key, _hotspot_value(item))))}</li>"
        for item in items
    )
    return f"""
<article>
  <h3>{escape(title)}</h3>
  <ul>{rows or "<li>No hotspots found.</li>"}</ul>
</article>"""


def _hotspot_value(item: dict[str, Any]) -> str:
    if "rule_coverage" in item:
        return f"{item['rule_coverage']:.0%}"
    if "risk_score" in item:
        return f"{item['risk_score']:.1f}"
    if "files" in item:
        return str(item["files"])
    return ""


_ASSESSMENT_CSS = """
:root {
  color-scheme: light;
  --bg: #f7f8fa;
  --ink: #18202a;
  --muted: #667085;
  --line: #d9dee7;
  --panel: #ffffff;
}
body {
  margin: 0;
  background: var(--bg);
  color: var(--ink);
  font: 14px/1.5 system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}
header {
  display: flex;
  justify-content: space-between;
  gap: 24px;
  align-items: baseline;
  padding: 24px 32px;
  background: #111827;
  color: white;
}
h1, h2 { margin: 0; }
h3 { margin: 0 0 8px; }
main { padding: 24px 32px 40px; }
section {
  margin: 0 0 24px;
  padding: 20px;
  background: var(--panel);
  border: 1px solid var(--line);
  border-radius: 6px;
}
.summary {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
  gap: 12px;
}
.summary article {
  border: 1px solid var(--line);
  border-radius: 6px;
  padding: 12px;
}
.summary span { display: block; color: var(--muted); }
.summary strong { font-size: 22px; }
.columns {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
  gap: 16px;
}
table { width: 100%; border-collapse: collapse; margin-top: 12px; }
th, td { text-align: left; border-bottom: 1px solid var(--line); padding: 8px; }
th { color: var(--muted); font-weight: 600; }
code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
li span { color: var(--muted); }
"""
