"""Shared helpers for j2py-wire generation targets."""

from __future__ import annotations

import ast
import re
from pathlib import Path

from j2py.wire.schema import WiringElement, WiringSidecar
from j2py.wiring_contract import translate_field_name

GENERATED_HEADER = "# Generated by j2py-wire - do not edit. Re-run j2py-wire generate to update."

_BUILTIN_TYPES = {
    "Any",
    "bool",
    "bytes",
    "dict",
    "float",
    "int",
    "list",
    "None",
    "object",
    "set",
    "str",
    "tuple",
}
_IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def type_modules(sidecars: list[WiringSidecar], translated_root: Path) -> dict[str, str]:
    modules: dict[str, str] = {}
    for sidecar in sidecars:
        module = sidecar.python_module(translated_root)
        for element in sidecar.elements:
            if element.kind == "class":
                modules[element.python_name] = module
    return modules


def base_type(type_name: str) -> str:
    return re.split(r"[\[|.]", type_name, maxsplit=1)[0].strip()


def should_import_type(type_name: str) -> bool:
    base = base_type(type_name)
    return bool(base and base not in _BUILTIN_TYPES and _IDENTIFIER_RE.match(base))


def provider_identity(element: WiringElement) -> str:
    component_name = element.spring.get("component_name")
    if isinstance(component_name, str) and component_name:
        return component_name
    return translate_field_name(element.python_name)


def parse_python(path: Path) -> ast.Module | None:
    if not path.is_file():
        return None
    try:
        return ast.parse(path.read_text(encoding="utf-8"))
    except (OSError, SyntaxError):
        return None


def annotation_name(annotation: ast.expr | None) -> str:
    if annotation is not None:
        return ast.unparse(annotation)
    return "object"


def list_of_dicts(value: object) -> list[dict[str, object]]:
    if not isinstance(value, list):
        return []
    return [item for item in value if isinstance(item, dict)]
